apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: todolist
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30174
